name: 'Install JQ'
description: 'Installs the cli tool JQ'
inputs:
  version:  # id of input
    description: 'Version to install'
    required: true
    default: 'latest'
runs:
  using: 'node16'
  main: 'dist/index.js'