name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: |
          echo "${{ env.test_var }}"
          echo "${GITHUB_PATH}"
      - run: |
          curl "https://api.github.com/repos/stedolan/jq/releases/latest" | jq '.html_url'
